name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "*/10 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  health_check_job:
    environment:
      name: status-update
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v3
      - name: Run Shell Script
        env:
          GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
        id: shell_script_run
        run: bash ./health-check.sh
